from dotenv import load_dotenv
import os


load_dotenv()

REDIS_HOST = os.getenv("REDIS_HOST", None)
REDIS_PORT = os.getenv("REDIS_PORT", None)

PROXY_HOST = os.getenv("PROXY_HOST", None)
PROXY_PORT = int(os.getenv("PROXY_PORT", None))
PROXY_PROTOCOL = os.getenv("PROXY_PROTOCOL", None)

SECRET_KEY = os.getenv("FAST_API_SECRET_KEY", None)
ALGORITHM = os.getenv("FAST_API_ALGORITHM", None)
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("FAST_API_ACCESS_TOKEN_EXPIRE_MINUTES", None))

TELEGRAM_INDEX_CHANNELS = os.getenv("TELEGRAM_INDEX_CHANNELS", None)
TELEGRAM_INDEX_MESSAGES = os.getenv("TELEGRAM_INDEX_MESSAGES", None)
TELEGRAM_INDEX_GROUPS = os.getenv("TELEGRAM_INDEX_GROUPS", None)
TELEGRAM_INDEX_USERS = os.getenv("TELEGRAM_INDEX_USERS", None)
TELEGRAM_INDEX_CHAT_MESSAGES = os.getenv("TELEGRAM_INDEX_CHAT_MESSAGES", None)

TELEGRAM_CHATS_MESSAGE_SEND_TOPIC = os.getenv("TELEGRAM_CHATS_MESSAGE_SEND_TOPIC", None)
TELEGRAM_UPDATE_MESSAGE = os.getenv("TELEGRAM_UPDATE_MESSAGE", None)
TELEGRAM_UPDATE_ACK_TOPIC = os.getenv("TELEGRAM_UPDATE_ACK_TOPIC", "telegram_update_ack")

RSS_INDEX_MESSAGES = os.getenv("RSS_INDEX_MESSAGES", None)

KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS", None)

MINIO_QUERIES_BUCKET_NAME=os.getenv("MINIO_QUERIES_BUCKET_NAME", None)
MINIO_TELEGRAM_CHANNEL_BUCKET_NAME=os.getenv("MINIO_TELEGRAM_CHANNEL_BUCKET_NAME", None)
MINIO_TELEGRAM_GROUP_BUCKET_NAME=os.getenv("MINIO_TELEGRAM_GROUP_BUCKET_NAME", None)
MINIO_TELEGRAM_USER_BUCKET_NAME=os.getenv("MINIO_TELEGRAM_USER_BUCKET_NAME", None)
MINIO_TELEGRAM_MEDIA_CHATS_BUCKET_NAME=os.getenv("MINIO_TELEGRAM_MEDIA_CHATS_BUCKET_NAME", None)

TELEGRAM_ACCOUNT_MANAGER_HOST = os.getenv("TELEGRAM_ACCOUNT_MANAGER_HOST", None)
