"""Create tables.

Revision ID: 5619e50895cb
Revises: 
Create Date: 2025-10-07 08:38:25.396581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5619e50895cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.BigInteger(), nullable=False),
    sa.Column('api_id', sa.BigInteger(), nullable=False),
    sa.Column('api_hash', sa.String(length=100), nullable=False),
    sa.Column('session_file', sa.String(length=100), nullable=False),
    sa.Column('process', sa.Integer(), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String(length=10)), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('session_file')
    )
    op.create_table('telegram_peers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=33), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('peer_id', sa.BigInteger(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('linked_peer_id', sa.BigInteger(), nullable=True),
    sa.Column('subscriber', sa.BigInteger(), nullable=True),
    sa.Column('is_channel', sa.Boolean(), nullable=True),
    sa.Column('on_waiting', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('peer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_peers')
    op.drop_table('telegram_accounts')
    # ### end Alembic commands ###
