services:

  delivery:
    build:
      context: ./delivery
    container_name: delivery
    image: delivery
    volumes:
      - ./.env:/code/.env
      - ./utils:/code/utils
      - ./conf:/code/conf
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 20s
      timeout: 10s
      retries: 10


networks:
  app-network:
    driver: bridge
